apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-nginx
  labels:
    # here we are defining a label of "app: my-nginx" at the deployment
    app: my-nginx 
spec: 
  # We can define how many replicas of the container that we want in our pod spec
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        # by using the label app: my-nginx that we used previously, we are effictively linking our pod template to the deployment
        app: my-nginx 
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine 
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" # 128 MB
            cpu: "200m" # 200 millicpu (.2 cpu or 20% of the cpu)
